env: "local" # dev, prod
storage_paths: "./storage/sso.db"
token_ttl: "1h"
server:
  port: "8000"
  host: "localhost"
db:
  port: "5432"
  host: "localhost"
  username: "postgres"
  dbname: "postgres"
  ssl_mode: "disable"
  password: "qwerty"