services:
  profile-proto:
    build:
      context: .
      dockerfile: ./proto/profile/Dockerfile
    image: profileserviceproto-go:v1.0
    volumes:
      - ./proto/profile:/opt/proto/profile
    command: >
      sh -c "protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative profile.proto"
    networks:
      - grpc

  notification-proto:
    build:
      context: .
      dockerfile: ./proto/notification/Dockerfile
    image: notificationeserviceproto-go:v1.0
    volumes:
      - ./proto/notification:/opt/proto/notification
    command: >
      sh -c "protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative notificationservice.proto"
    networks:
      - grpc

  profileservicetest:
    build:
      context: .
      dockerfile: ./profileservicetest/Dockerfile
    image: profileservice-go:v1.0
    ports:
      - "50501:50501"
    networks:
      - grpc
    depends_on:
      - profile-proto

  taskservice:
    build:
      context: .
      dockerfile: ./taskservice/Dockerfile
    image: taskservice-go:v2.0
    networks:
      - grpc
    depends_on:
      - profileservicetest
    environment:
      - SERVER_HOST=grpc-server:50501
    ports:
      - "8080:8080"

  notificationservice:
    build:
      context: .
      dockerfile: ./notificationservice/Dockerfile
    image: notificationservice-go:v2.0
    networks:
      - grpc
    depends_on:
      - notification-proto
    environment:
      - SERVER_HOST=grpc-server:50501
    ports:
      - "8080:8080"

  dapomogu_task_postgres:
    container_name: dapomogu_task_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dapomogu_password
      POSTGRES_DB: dapomogu_task_postgres_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./client/db-init/:/docker-entrypoint-initdb.d/
    ports:
      - "5435:5432"
    networks:
      - grpc
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - grpc
    depends_on:
      - dapomogu_task_postgres
    command: [
      "-path", "./taskservice/migrations",
      "-database", "postgres://postgres:dapomogu_password@dapomogu_task_postgres:5432/dapomogu_task_postgres_db?sslmode=disable",
      "up"
    ]

networks:
  grpc:
    driver: bridge

volumes:
  postgres: